### ISSUE TITLE
Move your tests into the test/ folder

### ISSUE THREAD

**Issue by jbueza** [NTmatter/LLBoy#2]

**Comment by NTmatter** [comment]
This might be a challenge in the context of the current project layout. I think it'll be doable with a little bit of re-jigging and reorganization to make use of actual linked libraries.

As a temporary workaround, I've renamed all the tests to be "test_$COMPONENT_$PART" such as test_cpu_arithmetic, allowing for a cleaner file list.

**Comment by jbueza** [comment]
:D

The node project has a pretty sweet structure: https://github.com/joyent/node

**Comment by NTmatter** [comment]
Definitely does. It looks like it was put together by someone who knows what they're doing -- I'll see what can be gleaned from it, but I suspect that there will still be a mess due to how I'm generating the LLVM Bitcode.
